config/routes.rb
Rails.application.routes.draw do
  
  root 'entry#index'
  get 'en' => 'entry#index'
  resources :tags
  resources :topics do
    resources :posts
  end
  resources :posts do 
    resources :comments
  end
    
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  has_many :comments
  has_many :taggings
  has_many :tags,through: :taggings
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :posts,through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :posts,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
end
def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  private
    def comment_params
      params.require(:comment).permit( :stuff)
    end
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController

def index
	@post=Post.all.paginate(page: params[:page], per_page: 5) 
end

def posts
@post=Post.all
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_topic
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = @topic.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = @topic.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = @topic.posts.build(post_params.except(:tags))
    create_or_delete_posts_tags(@post,params[:post][:tags])
    respond_to do |format|
      if @post.save
        format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    create_or_delete_posts_tags(@post,params[:post][:tags])
    respond_to do |format|
      if @post.update(post_params.except(:tags))
        format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def create_or_delete_posts_tags(post,tags)
    post.taggings.destroy_all
    tags = tags.strip.split(',')
    tags.each do |tag|
      post.tags << Tag.find_or_create_by(tag_name:tag)
    end  
  end

    def set_topic
      @topic=Topic.find(params[:topic_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = @topic.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :topic_id, :tag_name)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:tag_name, :post_id)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/Home/_header.html.erb
<nav class="navbar navbar-expand-lg me-auto bg-dark " data-bs-theme="dark">
  <div class="container-fluid">
    <div class="grid gap-3">
    <div class="p-2 g-col-6">
      <span class="navbar-brand bg-dark">Topic App</span>
      <%= link_to "Home", topics_path,class: "navbar-brand"%>
      <%= link_to "Add Topic", new_topic_path, class: "navbar-brand" %>
      <button type="button" class="btn btn-primary position-relative"><%= link_to "All Posts",en_path, class: "navbar-brand" %>
      <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
    <%= Post.count %>
  </span>
</button> 
  </div>
</div>
</div>
</nav>

app/views/comments/_comment.html.erb
<% unless !comment.persisted? %>
  <div class="card ">
   <div class="card-body">
    <%= comment.stuff %> | <%= link_to "Destroy Comment", [comment.post, comment], class: 'btn btn-outline-danger', data: {turbo_method: :delete,turbo_confirm: "Are you sure?"} %>
    </div>
  </div>

<% end %>

app/views/comments/_form.html.erb
<div class="card my-1">
  <div class="card-body">
    <p class="font-weight-bold">Comments</p>
    <%= form_with(model: [@post, @post.comments.build]) do |f| %>
      <div class="form-group">
        <%= f.label 'New comment' %>
        <%= f.text_area :stuff, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  </div>

app/views/entry/index.html.erb
<% @post.each do |post| %>
<div class="card border-primary mb-3" style="max-width: 18rem;">
  <h5 class="card-header"><strong><%= post.topic.name %> : <%= post.title %></strong></h5>
  <div class="card-body">
    <p class="card-text">"<%= post.body %>"</p>
    <% post.tags.each do |tag| %>
    <%= link_to tag, style:"text-decoration:none" do %>
      <span class="btn btn-outline-dark"><%= tag.tag_name.capitalize %></span>
    <% end %>
  <% end %>
  <div class="bl"><strong>Comments (<%= post.comments.count %>)</strong></div>
  <%= form_with(model: [post, post.comments.build]) do |f| %>
      <div class="form-group">
        <%= f.text_area :stuff, class: 'form-control', placeholder: "New Comment" %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <% end %>
  <div class="bl"><%= render post.comments %></div>
  </div>
</div>
<% end %>
<%= will_paginate @post, class: "apple_pagination" %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Topic_App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% if cookies[:moon] %>
    <%= stylesheet_link_tag 'application_dark', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% else %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'Home/header' %>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
        </br>
      <%= yield%>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: [@topic,post]) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form field-group">
    <%= form.text_field :title, class: "form-control", placeholder: "Title of Post" %>
  </div>

  <div class="form field-group">
    <%= form.text_area :body,class: "form-control", placeholdere: "Post content" %>
  </div>
<div class="form field-group">
    <%= form.text_field :tags, value: post.tags.map(&:tag_name).join(","), class: "form-control", placeholder: "Add Tag" %>
    </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <p>
    <strong>Topic:</strong>
    <%= post.topic.name%>
  </p>
  <strong>Tags:</strong>
  <% post.tags.each do |tag| %>
    <%= link_to tag, style:"text-decoration:none" do %>
      <span class="btn btn-secondary"><%= tag.tag_name.capitalize %></span>
    <% end %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", [@topic,@post] %> |
  <%= link_to "Back to posts", topic_posts_path(@topic) %>
</div>

app/views/posts/index.html.erb
<br/>
<table class="table table-striped table-bordered">
  <thead class="thead-light">
    <tr>
      <th>Title of Post</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <% @posts.each do |post| %>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Edit Post', edit_topic_post_path(@topic, post),class: 'btn btn-outline-secondary' %></td>
        <td><%= link_to 'Destroy Post', [@topic, post],class: 'btn btn-outline-danger', data: {'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Post', new_topic_post_path(@topic),class: 'btn btn-outline-primary' %> |
<%= link_to 'Back', [@topic],class: 'btn btn-outline-dark' %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", topic_posts_path(@topic) %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @post %>
<div>
  <%= link_to "Go to posts", topic_posts_path,class: 'btn btn-outline-secondary' %>
</div>

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tag_name, style: "display: block" %>
    <%= form.text_field :tag_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Name:</strong>
    <%= tag.tag_name %>
  </p>
  <% tag.taggings.each do |tagging| %>
    <h3>posts</h3>
    <%= render 'posts/post', post: tagging.post %>
    <hr/>
  <% end %>
</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tags</h1>

<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>
    <p>
      <%= link_to "Show this tag", tag %>
    </p>
  <% end %>
</div>

<%= link_to "New tag", new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tag %>

<div>
  <%= link_to "Edit this tag", edit_tag_path(@tag) %> |
  <%= link_to "Back to tags", tags_path %>

  <%= button_to "Destroy this tag", @tag, method: :delete %>
</div>

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">
  <p>
    <strong>Name:</strong>
    <%= topic.name %>
  </p>

</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/index.html.erb
  <div class="row row-cols-1 row-cols-md-4 g-4">
  <% @topics.each do |topic| %>
  <div class="col">
<div class="card text-center border-primary" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= topic.name%></h5>
    <h7><%= link_to "Click Here",topic_path(topic.id),class: 'btn btn-outline-primary'%></h7>
  </div>
</div>
</div>
<% end %>
</div>

app/views/topics/new.html.erb
<head>
<style>
.cred{ 
  color:red; 
}
</style>
</head>
<div class= "cred"><h3>You're Creating New Topic !</h3></div>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Back to topics", topics_path,class: 'btn btn-outline-secondary' %>
</div>

app/views/topics/show.html.erb
<style>
  .fr{
  color: red;
  }
</style>
<h2><div class="fr">Topic: <%=  @topic.name %></div></h2>
    <br/>
<div class="row row-cols-1 row-cols-md-4 g-4">
  <% for post in @topic.posts %>
  <div class="col">
<div class="card text-center border-secondary" style="width: 18rem;">
  <div class="card-body">
    <p class="card-text"><%= post.body %></p>
    <%= link_to "Show this post",[@topic,post],class: 'btn btn-outline-dark' %>
  </div>
</div>
</div>
<% end %>
</div>  
  <br/>
  <%= link_to 'Add Post', new_topic_post_path(@topic),class: 'btn btn-outline-primary'%>
  <%= link_to 'Available Posts', topic_posts_path(@topic),class: 'btn btn-outline-primary'%>
  <%= link_to "Back to topics", topics_path,class: 'btn btn-outline-secondary' %>